## 创建张量

```python
tf.constant(张量内容, dtype=数据类型)
```

In [1]:
import tensorflow as tf

a = tf.constant([1, 5], dtype=tf.int64)
print(a)
print(a.shape)
print(a.dtype)

tf.Tensor([1 5], shape=(2,), dtype=int64)
(2,)
<dtype: 'int64'>


`shape`中有几个逗号隔开的数字，就是有几维

将`numpy`类型的数据转换为`tensor`类型

```python
tf.convert_to_tensor(数据名， dtype=数据类型)
```

In [3]:
import numpy as np

a = np.arange(1,10)
d = tf.convert_to_tensor(a, dtype=tf.int32)
print(a)
print(d)

[1 2 3 4 5 6 7 8 9]
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


创建全零的`tensor`张量

```python
tf.zeros(维度)
```

In [5]:
c = tf.zeros(shape=(2,3))
c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

创建全1的`tensor`张量
```python
tf.ones(维度)
```

In [6]:
d = tf.ones(shape=(2,3))
d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

创建全指定数据张量
```python
tf.fill(维度, 指定的值)
```

In [7]:
e = tf.fill([2, 3], 10)
e

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10]], dtype=int32)>

生成正态分布的随机数，默认值为0，标准差为1
```python
tf.random.normal(维度, mean=均值, stddev=标准差)
```

In [8]:
f = tf.random.normal(shape=[2,3], mean=1, stddev=.5)
f

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.82506275, 2.2988374 , 1.1321012 ],
       [1.0544784 , 0.3067587 , 1.4552938 ]], dtype=float32)>

生成截断式的正态分布的随机数
```python
tf.random.truncated_normal(维度, mean=均值, stddev=标准差)
```
如果生成的数值在(均值-2*标准差，均值+2*标准差)之外的话会重新生成

In [12]:
j = tf.random.truncated_normal(shape=(2,3), mean=1, stddev=.5)
j

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.3488824 , 1.3713413 , 0.8954021 ],
       [0.98434776, 0.8150234 , 1.4957652 ]], dtype=float32)>

生成均匀分布的随机数
```python
tf.random.uniform(维度, maxval=最大值, minval=最小值)
```

In [13]:
h = tf.random.uniform(shape=(2,3), maxval=100, minval=50)
h

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[91.690254, 53.101273, 72.16043 ],
       [50.748016, 84.61701 , 78.71806 ]], dtype=float32)>

## 常量函数

强制`tensor`**转换数据类型**。
```python
tf.cast(张量名, dtype=数据类型)
```

In [14]:
x1 = tf.constant([1,5], dtype=tf.float32)
x2 = tf.cast(x1, dtype=tf.int64)
print(x1)
print(x2)

tf.Tensor([1. 5.], shape=(2,), dtype=float32)
tf.Tensor([1 5], shape=(2,), dtype=int64)


计算`tensor`中的**最小值**和**最大值**。
```python
tf.reduce_max(张量名)

tf.reduce_min(张量名)
```

In [15]:
x1_max = tf.reduce_max(x1)
x1_min = tf.reduce_min(x1)
print('x1中的最大值是{}，最小值是{}'.format(x1_max, x1_min))

x1中的最大值是5.0，最小值是1.0


计算`tensor`中的**均值**。
```python
tf.reduce_mean(张量名)
```

In [16]:
x1_mean = tf.reduce_mean(x1)
print('x1的均值是{}'.format(x1_mean))

x1的均值是3.0


计算`tensor`的**和**。
```python
tf.reduce_sum(张量名)
```

In [17]:
x1_sum = tf.reduce_sum(x1)
print('x1的和是{}'.format(x1_sum))

x1的和是6.0


使用`axis`属性控制**计算的方向**，在二维张量中`axis=0`是指对列操作，`axis=1`是指对行操作。

In [21]:
x = tf.constant([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
x_max_1 = tf.reduce_max(x, axis=1)
x_max_1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [23]:
x_max_0 = tf.reduce_max(x, axis=0)
x_max_0

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 7], dtype=int32)>

In [24]:
x_sum_1 = tf.reduce_sum(x, axis=1)
x_sum_1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 12, 18], dtype=int32)>

In [25]:
x_sum_0 = tf.reduce_sum(x, axis=0)
x_sum_0

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 12, 15], dtype=int32)>

### 标记可训练的变量

`tf.Variabe()`将变量标记为`可训练`的变量，被标记的变量在反向传播的过程中将被记录梯度信息。在神经网络中标记待训练的参数。

In [27]:
#初始化参数W
w = tf.Variable(tf.random.normal([2,4], mean=0, stddev=1))

### 常用的向量计算

`tf.add()`张量的和

`tf.subtract()`张量的差

`tf.multiply()`张量的积

`tf.divide()`张量的除

`tf.square()`张量的平方

`tf.pow()`张量的次方

`tf.sqrt()`张量的开放

`tf.matmul()`张量的矩阵乘法

In [43]:
x = tf.constant([1,2])
w = tf.constant([5,6])

tf.add(x,w)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 8], dtype=int32)>

In [30]:
tf.subtract(x,w)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-4, -4], dtype=int32)>

In [31]:
tf.multiply(x,w)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 12], dtype=int32)>

In [32]:
tf.divide(x,w)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.2       , 0.33333333])>

In [33]:
tf.square(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [34]:
tf.square(w)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([25, 36], dtype=int32)>

In [36]:
tf.pow(x, 2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [46]:
a = tf.ones([3,2])
b = tf.fill([2,3], 3.)
#注意数据类型要一致
tf.matmul(a, b)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

### 特征和标签配对

`tf.data.Dataset.from_tensor_slices`可以将输入的特征和对应的标签进行绑定，构建数据集。

```python
data = tf.data.Dataset.from_tensor_slices((输入特征，标签))
```

支持`numpy`格式的数据输入。

In [47]:
features = tf.constant([[1,2],[2,3]])
labels = tf.constant([1,0])
data = tf.data.Dataset.from_tensor_slices((features,labels))
print(data)

<TensorSliceDataset shapes: ((2,), ()), types: (tf.int32, tf.int32)>


In [49]:
for element in data:
    print(element)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


### 对指定参数求导

`tf.GradientTape`可以实现函数中的某个参数的求导运算。

```python
with tf.GradientTape() as tape:
    ....
tape.gradient(函数，对谁求导)
```

In [50]:
with tf.GradientTape() as tape:
    w = tf.Variable(tf.constant(3.))
    loss = tf.pow(w, 2)
grad = tape.gradient(loss, w)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


$$
loss = w^2
$$

$$
\frac{\partial_{w^2}}{\partial_{w}} = 2w = 2 * 3.0 = 6.0
$$

### 枚举

`enumerate`是python内建函数，可以遍历每个元素（例如列表、元组和字符串），组合为：**索引 元素**，常在for 中使用

In [51]:
seq = ['one', 'two', 'three']
for i, element in enumerate(seq):
    print('{} -> {}'.format(i, element))

0 -> one
1 -> two
2 -> three


### 独热编码
`tf.one_hot`是tf总自带的**独热编码**，在分类问题中，常用独热编码做标签，标记类别：1表示是，0表示非

```python
tf.one_hot(待转换数据, depth=几分类)
```

In [55]:
classes = 4
#表示输入的元素最小为0，最大为4
labels = tf.constant([1, 0, 3, 2])
tf.one_hot(labels, depth=classes)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

### 激活函数 softmax

假如分类问题输出的是`[1.01, 2.02, -0.33, 3.33]`这样的输出不符合概率分布，只有符合概率分布的输出才可以于**独热码**比较

$$
\frac{e^{y_i}}{\sum_{j=0}^{n}e^{y_i}}
$$

用该公式计算可知：
$$
\frac{e^{y_0}}{e^{y_0}+e^{y_1}+e^{y_2}+e^{y_3}} = \frac{e^1.01}{e^{1.01}+e^{2.02}+e^{-0.33}+e^{3.33}} \approx 0.07
$$

$$
\frac{e^{y_1}}{e^{y_0}+e^{y_1}+e^{y_2}+e^{y_3}} = \frac{e^2.02}{e^{1.01}+e^{2.02}+e^{-0.33}+e^{3.33}} \approx 0.194
$$

$$
\frac{e^{y_2}}{e^{y_0}+e^{y_1}+e^{y_2}+e^{y_3}} = \frac{e^{-0.33}}{e^{1.01}+e^{2.02}+e^{-0.33}+e^{3.33}} \approx 0.018
$$

$$
\frac{e^{y_3}}{e^{y_0}+e^{y_1}+e^{y_2}+e^{y_3}} = \frac{e^3.33}{e^{1.01}+e^{2.02}+e^{-0.33}+e^{3.33}} \approx 0.717
$$

当n分类的n个输出$(y_0, y_1, ...y_{n-1})$通过`tf.softmax()`函数后会更符合概率分布。

In [56]:
y = tf.constant([1.01, 2.02, -0.33, 3.33])
y_pro = tf.nn.softmax(y)
print('经过softmax后的y = {}'.format(y_pro))

经过softmax后的y = [0.07050634 0.19358228 0.01846178 0.71744955]


In [57]:
tf.reduce_sum(y_pro)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

### 参数自更新 assign_sub

负值操作，更新参数的值并返回新的值。

调用`assign_sub`前，先用`tf.Variable`定义变量`w`为可训练（可自更新）

```python
w.assign_sub(n) # w-=n
```

In [58]:
w = tf.Variable(4)
w.assign_sub(1)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


### 返回张量的最大值索引

`tf.argmax()`返回张量沿指定维度最大值的索引号

```python
tf.argmax(张量名称, axis=操作轴)
```

In [62]:
import numpy as np

test = np.array([[1, 2, 3], [3, 8, 5], [9, 6, 7], [9, 6, 11]])
print(test)
print(tf.argmax(test, axis=0))
print(tf.argmax(test, axis=1))
print(tf.argmin(test, axis=0))
print(tf.argmin(test, axis=1))

[[ 1  2  3]
 [ 3  8  5]
 [ 9  6  7]
 [ 9  6 11]]
tf.Tensor([2 1 3], shape=(3,), dtype=int64)
tf.Tensor([2 1 0 2], shape=(4,), dtype=int64)
tf.Tensor([0 0 0], shape=(3,), dtype=int64)
tf.Tensor([0 0 1 1], shape=(4,), dtype=int64)
